<?php
namespace Creatiff\Forms\UI;

use Creatiff\Forms\Cast;
use Creatiff\Forms\Component;
use Creatiff\Forms\Exception;
use Creatiff\Forms\Property;
use Creatiff\Forms\UI\Store\Proxy\Memory;
use Creatiff\Forms\UI\Store\Proxy;

class Store extends Component{

	/**
	 * @var array
	 */
	private $data = null;

	/**
	 * @var bool
	 */
	private $autoLoad = false;
	/**
	 * @var Proxy
	 */
	private $proxy = null;

	/**
	 * @var bool
	 */
	private $remoteSort = false;

	public function __construct(Component $owner = null)
	{
		parent::__construct($owner); // TODO: Change the autogenerated stub
	}


	/**
	 * @param boolean $autoload
	 */
	public function setAutoLoad($autoload)
	{
		$this->autoLoad = Cast::bool($autoload);
	}

	/**
	 * @return boolean
	 */
	public function getAutoLoad()
	{
		return $this->autoLoad;
	}

	/**
	 * @param array $data
	 */
	public function setData($data)
	{
		if(is_string($data)){
			$data = json_decode($data,true);
		}

		if(!is_array($data)){
			throw new Exception('Wrong data in store');
		}

		$this->data = $data;
	}

	/**
	 * @return array
	 */
	public function getData()
	{
		return $this->data;
	}

	/**
	 * @param Proxy $proxy
	 */
	public function setProxy(Proxy $proxy)
	{
		$this->proxy = $proxy;
	}

	/**
	 * @return null
	 */
	public function getProxy()
	{
		return $this->proxy;
	}

	/**
	 * @param boolean $remoteSort
	 */
	public function setRemoteSort($remoteSort)
	{
		$this->remoteSort = Cast::bool($remoteSort);
	}

	/**
	 * @return boolean
	 */
	public function getRemoteSort()
	{
		return $this->remoteSort;
	}



}